apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaletestapp-deployment
  namespace: ns-scaletest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaletestapp
  template:
    metadata:
      labels:
        app: scaletestapp
    spec:
      containers:
        - name: scaletestapp
          image: shestera/scaletestapp
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "20Mi"
              cpu: "100m"
            limits:
              memory: "30Mi"
              cpu: "500m"
              